IMAGE_NAME = "bento/debian-12"
 
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
 
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
 
    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
 
        debian.vm.network "forwarded_port", guest: 80, host: 2207, host_ip: "127.0.0.1"
        debian.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
        debian.vm.hostname = "debian"
    end
 
    config.vm.provision "file", source: "ssh.pub", destination: "~/.ssh/me.pub"
 
    config.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
        sudo apt update -y
        sudo apt install -y apache2
        sudo systemctl enable apache2
        sudo systemctl start apache2
        if command -v ufw >/dev/null 2>&1; then
            sudo ufw allow 'Apache'
        fi
    SHELL
end